-- =============================================================
-- 【已废弃】此文件不再是建表依据，请勿据此建库。
--
-- 原因：本脚本与 Hibernate 实体的实际映射不一致——
--   * 枚举字段实际为 MySQL 原生 ENUM(...)，此处写的是 VARCHAR(20)
--   * 时间字段实际为 DATETIME(6)，此处写的是 DATETIME
-- 若不慎用它建库，ddl-auto=validate 会直接失败。
--
-- 现状：建表与结构变更已由各服务自己的 Flyway 脚本接管，
--       每个服务只维护自己领域的表，历史表相互独立：
--
--   auth-service/src/main/resources/db/migration/
--       V1__init_auth.sql                 u_r_sys_user, u_r_user_rating
--   aid-service/src/main/resources/db/migration/
--       V1__init_aid.sql                  u_r_aid_request, u_r_aid_rating,
--                                         u_r_aid_helper_review
--       V2__indexes_aid.sql               求助域查询索引
--       V3__normalize_aid_board.sql       归一化 board 列
--   community-service/src/main/resources/db/migration/
--       V1__init_community.sql            u_r_post, u_r_post_comment,
--                                         u_r_post_like, u_r_post_view, u_r_plaza_hot
--       V2__indexes_community.sql         社区域查询索引
--       V3__normalize_post_channel.sql    归一化 channel 列
--   ad-service/src/main/resources/db/migration/
--       V1__init_ad.sql                   u_r_ad
--       V2__indexes_ad.sql                广告位索引
--
-- 新增或修改表结构时：在对应服务下追加一个 V{n}__描述.sql，
-- 不要修改已经执行过的脚本。
-- =============================================================
